name = "Mohammed Obaid"

print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.title())
print(name.swapcase())
print(name.center(50, "*"))
print(name.ljust(50, "*"))
print(name.rjust(50, "*"))
print(name.zfill(50))
print(name.count("m"))
print(name.count("m", 0, 5))
print(name.find("m"))
print(name.find("m", 0, 5))
print(name.rfind("m"))
print(name.rfind("m", 0, 5))
print(name.index("m"))
print(name.index("m", 0, 5))
print(name.rindex("m"))
print(name.rindex("m", 0, 5))
print(name.startswith("m"))
print(name.startswith("m", 0, 5))
print(name.endswith("m"))
print(name.endswith("m", 0, 5))
print("*********")
print(name.isalnum())
print(name.isalpha())
print(name.isdigit())
print(name.islower())
print(name.isupper())
print(name.istitle())
print(name.isspace())
print(name.isdecimal())
print(name.isnumeric())
print(name.isidentifier())
print(name.isprintable())
print(name.isascii())
print("*********")
print(name.split())
print(name.split("m"))
print(name.split("m", 1))
print(name.rsplit("m"))
print(name.rsplit("m", 1))
print(name.partition("m"))
print(name.rpartition("m"))
print(name.join("m"))
print(name.join(["mohammed", "obaid"]))
print(name.join(["mohammed", "obaid", "mohammed", "obaid"]))
print("*********")
print(name.replace("m", "M"))
print(name.replace("m", "M", 1))
name = "Mohammed Obaid"
print(name)
print(name.strip())
print(name.lstrip())
print(name.rstrip())
print(name.replace(" ", ""))
print(name.replace(" ", "", 1))
